name: electrs

on:
  push:

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    strategy:
      matrix:
        build-args:
          [
            --locked,
          ]

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Install Rust
        run: rustup component add rustfmt clippy

      - name: Remove build-essential
        run: sudo apt remove build-essential

      - name: Run
        run: cargo run --release --bin segfault
